package cryptography;

import java.io.File;
import java.util.HashMap;

import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButtonMenuItem;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.undo.UndoManager;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;

import javax.swing.JMenu;
import javax.swing.JMenuItem;

import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;


/**
 * @author lindelof
 * @since Nov 15, 2013
 *
 */
public class Editor extends javax.swing.JFrame {

    Utility utility;
    UndoManager undo;
    HashMap<Integer, JRadioButtonMenuItem> mode_menu_list;
    int initial_win_width = 800;
    int initial_win_height = 600;
    
    String appTitle = "Encryption Emulator";
    String version = "1.0";

    /**
     * Creates new form Editor
     */
    public Editor() {

    	
    	setTitle("New" + " - "+appTitle);
        initComponents();

        initMode();

        setMode();

        undo = new UndoManager();
        text.getDocument().addUndoableEditListener(undo);  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JEditorPane();
        menu = new javax.swing.JMenuBar();
        menu.setSize(new Dimension(600, 50));
        menu_file = new javax.swing.JMenu();
        menu_new = new javax.swing.JMenuItem();
        menu_open = new javax.swing.JMenuItem();
        menu_save = new javax.swing.JMenuItem();
        menu_save_as = new javax.swing.JMenuItem();
        menu_edit = new javax.swing.JMenu();
        menu_copy = new javax.swing.JMenuItem();
        menu_cut = new javax.swing.JMenuItem();
        menu_paste = new javax.swing.JMenuItem();
        seperator = new javax.swing.JPopupMenu.Separator();
        menu_undo = new javax.swing.JMenuItem();
        menu_redo = new javax.swing.JMenuItem();
        mnOperations = new javax.swing.JMenu();
        menu_read_pos = new javax.swing.JMenuItem();
        menu_save_pos = new javax.swing.JMenuItem();
        menu_cut_file = new javax.swing.JMenuItem();
        menu_integrity_check = new javax.swing.JMenuItem();
        menu_find_user = new javax.swing.JMenuItem();
        menu_get_file_length = new javax.swing.JMenuItem();
        menu_mode = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        
        setSize(new Dimension(initial_win_width, initial_win_height));
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int screen_width = (int)screenSize.getWidth();
        int screen_height = (int)screenSize.getHeight();
        setLocation((screen_width - initial_win_width)/2,(screen_height - initial_win_height)/2);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setViewportView(text);

        getContentPane().add(jScrollPane1);

        menu_file.setText("File");

        menu_new.setText("New");
        menu_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_newActionPerformed(evt);
            }
        });
        menu_file.add(menu_new);

        menu_open.setText("Open");
        menu_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_openActionPerformed(evt);
            }
        });
        menu_file.add(menu_open);

        menu_save.setText("Save");
        menu_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_saveActionPerformed(evt);
            }
        });
        menu_file.add(menu_save);

        menu_save_as.setText("Save as");
        menu_save_as.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_save_asActionPerformed(evt);
            }
        });
        
        mnLoginreset = new JMenu("Reset");
        menu.add(mnLoginreset);
        menu_setpass = new javax.swing.JMenuItem();
        mnLoginreset.add(menu_setpass);
        
                menu_setpass.setText("Reset User");
                menu_setpass.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        menu_setpassActionPerformed(evt);
                    }
                });
        menu_file.add(menu_save_as);

        menu.add(menu_file);

        menu_edit.setText("Edit");

        menu_copy.setText("Copy");
        menu_copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_copyActionPerformed(evt);
            }
        });
        menu_edit.add(menu_copy);

        menu_cut.setText("Cut");
        menu_cut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cutActionPerformed(evt);
            }
        });
        menu_edit.add(menu_cut);

        menu_paste.setText("Paste");
        menu_paste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pasteActionPerformed(evt);
            }
        });
        menu_edit.add(menu_paste);
        menu_edit.add(seperator);

        menu_undo.setText("Undo");
        menu_undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_undoActionPerformed(evt);
            }
        });
        menu_edit.add(menu_undo);

        menu_redo.setText("Redo");
        menu_redo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_redoActionPerformed(evt);
            }
        });
        menu_edit.add(menu_redo);

        menu.add(menu_edit);

        mnOperations.setText("Features");

        menu_read_pos.setText("Read from Position");
        menu_read_pos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_read_posActionPerformed(evt);
            }
        });
        mnOperations.add(menu_read_pos);

        menu_save_pos.setText("Save to Position");
        menu_save_pos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_save_posActionPerformed(evt);
            }
        });
        mnOperations.add(menu_save_pos);

        menu_cut_file.setText("Cut File");
        menu_cut_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cut_fileActionPerformed(evt);
            }
        });
        mnOperations.add(menu_cut_file);

        menu_integrity_check.setText("Check Integrity");
        menu_integrity_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_integrity_checkActionPerformed(evt);
            }
        });
        mnOperations.add(menu_integrity_check);

        menu_find_user.setText("Find User");
        menu_find_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_find_userActionPerformed(evt);
            }
        });
        mnOperations.add(menu_find_user);

        menu_get_file_length.setText("Get File Length");
        menu_get_file_length.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_get_file_lengthActionPerformed(evt);
            }
        });
        mnOperations.add(menu_get_file_length);

        menu.add(mnOperations);

        menu_mode.setText("Mode");
        menu_mode_efs = new javax.swing.JRadioButtonMenuItem();
        menu_mode_efs.setSelected(true);
        
                menu_mode_efs.setText("EFS");
                menu_mode_efs.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        menu_mode_efsActionPerformed(evt);
                    }
                });
                menu_mode.add(menu_mode_efs);

        menu.add(menu_mode);

        setJMenuBar(menu);
        
        mnAbout = new JMenu("About");
        menu.add(mnAbout);
        
        mntmAbout = new JMenuItem("About");
        mntmAbout.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
        		menu_aboutActionPerformed(evt);
        	}
        });
        mnAbout.add(mntmAbout);

        //pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_openActionPerformed
        try {
            
            File file = utility.set_dir();
            if (file == null) {
                return;
            }
            utility.dir = file;
            int len = utility.length(file.getAbsolutePath(), utility.password);

            byte[] ba = utility.read(file.getAbsolutePath(), 0, len, utility.password);
            

            String s = Utility.byteArray2String(ba);

            if (s != null) {
                text.setText(s);
            }
             
            setTitle(utility.dir + " - " + appTitle);
            
        } catch (Exception ex) {
            if (ex instanceof PasswordIncorrectException) {
                javax.swing.JOptionPane.showMessageDialog(null, "Incorrect password");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Cannot open file");
            }
        }
    }//GEN-LAST:event_menu_openActionPerformed

    private void menu_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_saveActionPerformed
        
        try {
            if (utility.dir == null) {


                File file = utility.set_dir();
                if (file == null) {
                    return;
                }

                utility.create(file.getAbsolutePath(), utility.username, utility.password);
                utility.dir = file;

            }

            utility.write(utility.dir.getAbsolutePath(), 0, text.getText().getBytes("UTF-8"), utility.password);
            utility.cut(utility.dir.getAbsolutePath(), text.getText().length(), utility.password);
            
            setTitle(utility.dir + " - " + appTitle);
        } catch (Exception ex) {
            if (ex instanceof PasswordIncorrectException) {
                javax.swing.JOptionPane.showMessageDialog(null, "Incorrect password");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Cannot write to file");
            }
        }

    }//GEN-LAST:event_menu_saveActionPerformed

    private void menu_save_asActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_save_asActionPerformed
        
        try {
            utility.dir = null;


            File file = utility.set_dir();
            if (file == null) {
                return;
            }
            utility.create(file.getAbsolutePath(), utility.username, utility.password);
            utility.dir = file;


            utility.write(utility.dir.getAbsolutePath(), 0, text.getText().getBytes("UTF-8"), utility.password);
            utility.cut(utility.dir.getAbsolutePath(), text.getText().length(), utility.password);
            
            setTitle(utility.dir + " - " + appTitle);
        } catch (Exception ex) {
            if (ex instanceof PasswordIncorrectException) {
                javax.swing.JOptionPane.showMessageDialog(null, "Incorrect password");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Cannot write to file");
            }
        }
    }//GEN-LAST:event_menu_save_asActionPerformed

    private void menu_copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_copyActionPerformed
        
        text.copy();

    }//GEN-LAST:event_menu_copyActionPerformed

    private void menu_cutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cutActionPerformed
        
        text.cut();
    }//GEN-LAST:event_menu_cutActionPerformed

    private void menu_pasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pasteActionPerformed
        
        text.paste();
    }//GEN-LAST:event_menu_pasteActionPerformed

    private void menu_undoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_undoActionPerformed
        
        if (undo.canUndo()) {
            undo.undo();
        }
    }//GEN-LAST:event_menu_undoActionPerformed

    private void menu_redoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_redoActionPerformed
       
        if (undo.canRedo()) {
            undo.redo();
        }
    }//GEN-LAST:event_menu_redoActionPerformed

    private void menu_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_newActionPerformed
       
        utility.dir = null;
        text.setText("");
        
        setTitle("New" + " - " + appTitle);

    }//GEN-LAST:event_menu_newActionPerformed

    private void menu_mode_efsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_mode_efsActionPerformed
        
        Config.MODE = Config.MODE_EFS;
        setMode();
    }//GEN-LAST:event_menu_mode_efsActionPerformed
    
    private void menu_aboutActionPerformed(java.awt.event.ActionEvent evt){
    	
    	JDialog aboutDialog = new JDialog(this,true);
    	aboutDialog.setTitle("About");
    	
    	aboutDialog.setResizable(false); 	
		JPanel aboutContentPane = new JPanel();
		aboutContentPane.setEnabled(false);
		aboutContentPane.setLayout(new BorderLayout());
		aboutContentPane.add(getAboutVersionLabel(), BorderLayout.CENTER);
		aboutContentPane.setOpaque(true);
		Color color = new Color(1, 1, 1, 1);//UIManager.getColor ( "Panel.background" );
		aboutContentPane.setBackground(color);
		
		aboutDialog.setContentPane(aboutContentPane);   
		aboutDialog.pack();
		aboutDialog.setSize(new Dimension(180, 120));
		aboutDialog.setLocationRelativeTo(this);
    	aboutDialog.setVisible(true);
    	
    }
    
    private JTextArea getAboutVersionLabel(){
    	
		JTextArea aboutVersionLabel = new JTextArea();
		aboutVersionLabel.setLineWrap(true);
		aboutVersionLabel.setBackground(UIManager.getColor("TextArea.disabledBackground"));
		aboutVersionLabel.setEditable(false);
    	String label = "\n     " + appTitle;
    	label +=       "\n     Version " + version;
    	label +=       "\n     Author: YIDAN ZHENG";
    	
    	aboutVersionLabel.setText(label);
    	return aboutVersionLabel;
    }

    private void menu_setpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_setpassActionPerformed
        
        utility.set_username_password();
    }//GEN-LAST:event_menu_setpassActionPerformed

    private void menu_save_posActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_save_posActionPerformed
        
        try {

            JPanel loginPanel = new JPanel();
            loginPanel.setLayout(new java.awt.GridLayout(1, 2));

            JLabel start_tag = new JLabel();
            JTextField start_field = new JTextField();

            start_tag.setText("start at position");
            loginPanel.add(start_tag);
            loginPanel.add(start_field);



            int okCxl = JOptionPane.showConfirmDialog(null, loginPanel, "Enter Password", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

            int start = 0, len = 0;

            if (okCxl == JOptionPane.OK_OPTION) {
                //len = Integer.parseInt(new String(len_field.getText()));
                start = Integer.parseInt(new String(start_field.getText()));
                if (utility.dir == null) {


                    File file = utility.set_dir();
                    if (file == null) {
                        return;
                    }

                    //utility.create(file.getAbsolutePath(), utility.username, utility.password);
                    utility.dir = file;

                }

                utility.write(utility.dir.getAbsolutePath(), start, text.getText().getBytes("UTF-8"), utility.password);

            }



        } catch (Exception ex) {
            if (ex instanceof PasswordIncorrectException) {
                javax.swing.JOptionPane.showMessageDialog(null, "Incorrect password");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Cannot write to file");
            }
        }
    }//GEN-LAST:event_menu_save_posActionPerformed

    private void menu_read_posActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_read_posActionPerformed
        

        try {
            JPanel loginPanel = new JPanel();
            loginPanel.setLayout(new java.awt.GridLayout(2, 2));

            JLabel start_tag = new JLabel();
            JTextField start_field = new JTextField();

            start_tag.setText("start at position");
            loginPanel.add(start_tag);
            loginPanel.add(start_field);

            JLabel len_tag = new JLabel();
            JTextField len_field = new JTextField();

            len_tag.setText("length");
            loginPanel.add(len_tag);
            loginPanel.add(len_field);

            int okCxl = JOptionPane.showConfirmDialog(null, loginPanel, "Enter Password", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

            int start = 0, len = 0;

            if (okCxl == JOptionPane.OK_OPTION) {
                len = Integer.parseInt(new String(len_field.getText()));
                start = Integer.parseInt(new String(start_field.getText()));
                File file = utility.set_dir();
                if (file == null) {
                    return;
                }
                utility.dir = file;
                //int len = utility.length(file.getAbsolutePath(), utility.password);

                byte[] ba = utility.read(file.getAbsolutePath(), start, len, utility.password);

                String s = Utility.byteArray2String(ba);

                if (s != null) {
                    text.setText(s);
                }
            }



            

        } catch (Exception ex) {
            if (ex instanceof PasswordIncorrectException) {
                javax.swing.JOptionPane.showMessageDialog(null, "Incorrect password");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Cannot read the file");
            }
        }
    }//GEN-LAST:event_menu_read_posActionPerformed

    private void menu_cut_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cut_fileActionPerformed
        
        try {
            JPanel loginPanel = new JPanel();
            loginPanel.setLayout(new java.awt.GridLayout(1, 2));

            JLabel start_tag = new JLabel();
            JTextField start_field = new JTextField();

            start_tag.setText("remaining length");
            loginPanel.add(start_tag);
            loginPanel.add(start_field);



            int okCxl = JOptionPane.showConfirmDialog(null, loginPanel, "Enter Password", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

            int start = 0, len = 0;

            if (okCxl == JOptionPane.OK_OPTION) {
                //len = Integer.parseInt(new String(len_field.getText()));
                len = Integer.parseInt(new String(start_field.getText()));
                if (utility.dir == null) {


                    File file = utility.set_dir();
                    if (file == null) {
                        return;
                    }

                    //utility.create(file.getAbsolutePath(), utility.username, utility.password);
                    utility.dir = file;

                }

                utility.cut(utility.dir.getAbsolutePath(), len, utility.password);
            }






        } catch (Exception ex) {
            if (ex instanceof PasswordIncorrectException) {
                javax.swing.JOptionPane.showMessageDialog(null, "Incorrect password");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Cannot cut the file");
            }
        }
    }//GEN-LAST:event_menu_cut_fileActionPerformed

    private void menu_integrity_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_integrity_checkActionPerformed
        
        try {


            File file = utility.set_dir();
            if (file == null) {
                return;
            }

            boolean b = utility.check_integrity(file.getAbsolutePath(), utility.password);

            if (b) {
                javax.swing.JOptionPane.showMessageDialog(null, "The file has NOT been modified");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "The file has been modified");
            }

        } catch (Exception ex) {
            if (ex instanceof PasswordIncorrectException) {
                javax.swing.JOptionPane.showMessageDialog(null, "Incorrect password");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Cannot read the file");
            }
        }
    }//GEN-LAST:event_menu_integrity_checkActionPerformed

    private void menu_find_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_find_userActionPerformed
        try {
            
            File file = utility.set_dir();
            if (file == null) {
                return;
            }
            String user = utility.findUser(file.getAbsolutePath());

            javax.swing.JOptionPane.showMessageDialog(null, "The user created the file is " + user);
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(null, "Cannot read the file");
        }

    }//GEN-LAST:event_menu_find_userActionPerformed

    private void menu_get_file_lengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_get_file_lengthActionPerformed
        
        try {
            
            File file = utility.set_dir();
            if (file == null) {
                return;
            }
            int len = utility.length(file.getAbsolutePath(), utility.password);

            javax.swing.JOptionPane.showMessageDialog(null, "The length of the file is " + len);
        } catch (Exception ex) {
            if (ex instanceof PasswordIncorrectException) {
                javax.swing.JOptionPane.showMessageDialog(null, "Incorrect password");
            } else {
                javax.swing.JOptionPane.showMessageDialog(null, "Cannot read the file");
            }
        }
    }//GEN-LAST:event_menu_get_file_lengthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Editor editor = new Editor();
                editor.setVisible(true);
                editor.utility.set_username_password();
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem menu_copy;
    private javax.swing.JMenuItem menu_cut;
    private javax.swing.JMenuItem menu_cut_file;
    private javax.swing.JMenu menu_edit;
    private javax.swing.JMenu mnOperations;
    private javax.swing.JMenu menu_file;
    private javax.swing.JMenuItem menu_find_user;
    private javax.swing.JMenuItem menu_get_file_length;
    private javax.swing.JMenuItem menu_integrity_check;
    private javax.swing.JMenu menu_mode;
    private javax.swing.JRadioButtonMenuItem menu_mode_efs;
    private javax.swing.JMenuItem menu_new;
    private javax.swing.JMenuItem menu_open;
    private javax.swing.JMenuItem menu_paste;
    private javax.swing.JMenuItem menu_read_pos;
    private javax.swing.JMenuItem menu_redo;
    private javax.swing.JMenuItem menu_save;
    private javax.swing.JMenuItem menu_save_as;
    private javax.swing.JMenuItem menu_save_pos;
    private javax.swing.JMenuItem menu_setpass;
    private javax.swing.JMenuItem menu_undo;
    private javax.swing.JPopupMenu.Separator seperator;
    private javax.swing.JEditorPane text;
    private JMenu mnAbout;
    private JMenuItem mntmAbout;
    private JMenu mnLoginreset;
    // End of variables declaration//GEN-END:variables

    private void setMode() {
        for (int key : mode_menu_list.keySet()) {
            if (key == Config.MODE) {
                mode_menu_list.get(key).setSelected(true);

            } else {
                mode_menu_list.get(key).setSelected(false);
            }
        }

        switch (Config.MODE) {
            case Config.MODE_EFS:
                utility = new EFS(this);
                text.setText("");
                break;
        }
    }

    private void initMode() {
        mode_menu_list = new HashMap<Integer, JRadioButtonMenuItem>();
        mode_menu_list.put(Config.MODE_EFS, menu_mode_efs);
    }
}
